# Generated by Django 2.0.3 on 2020-10-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='category',
            field=models.CharField(blank=True, default='sensor', max_length=10),
        ),
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, default='device name', max_length=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
