# Generated by Django 2.0.3 on 2020-10-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20201026_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='reading',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
